name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  set_env_vars:
    runs-on: ubuntu-latest
    outputs:
      ligo_container: ${{ steps.save_var.outputs.ligo_container }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - id: save_var
        run: echo "ligo_container=ligolang/ligo:"`make -s ligo-version` >> $GITHUB_OUTPUT

  build:
    needs: set_env_vars
    runs-on: ubuntu-latest
    container: ${{ needs.set_env_vars.outputs.ligo_container }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install ligo dependencies
        run: /root/ligo install
      - name: Build
        run: LIGO=/root/ligo make build
      - name: Test
        run: LIGO=/root/ligo make test
      - name: Package
        run: make tarball-app
      - name: Upload artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: _build/*.tar.gz

  deploy:
    needs: [set_env_vars, build-auditor]
    runs-on: ubuntu-latest
    container: ${{ needs.set_env_vars.outputs.ligo_container }}
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Download auditor artifact
        uses: actions/download-artifact@v3
        with:
          name: app
          path: _build/
      - name: Unzip artifact
        run:
          tar -zxvf _build/app-.tar.gz
      - name: Deploy contract on testnet
        shell: bash
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          LIGO=/root/ligo make deploy
          ./_build/tezos-client --endpoint https://kathmandunet.tezos.marigold.dev list known contracts >> $GITHUB_STEP_SUMMARY
